---
- name: Install cockpit-ws
  package: name={{ cockpit_pkgs | join (',') }} state=present
  vars:
    cockpit_pkgs:
    - cockpit-ws
    - cockpit-shell
    - cockpit-bridge
    - cockpit-docker
    - "{{ cockpit_plugins }}"
  when: not openshift.common.is_containerized | bool

- name: Enable cockpit-ws
  systemd:
    name: cockpit.socket
    enabled: true
    state: started
  when: not openshift.common.is_containerized | bool
